import { isPlainObject } from "./util.js";
import type { LensSpec } from "./types.js";

const paramTypes: Record<string, string> = {
  string: "string",
  number: "number",
  integer: "number",
  boolean: "boolean",
};

const primitiveTypes: Record<string, string> = { ...paramTypes, null: "null" };

/**
 * TypeScript source for typed bindings over a set of lens documents: a
 * `Lenses` map (params + result per lens, keyed by both scoped name and
 * shortname) and a `TypedLensClient` whose `call` is typed against it.
 */
export function generateTsSdk(specs: LensSpec[]): string {
  const sorted = [...specs].sort((a, b) => a.name.localeCompare(b.name));
  const known = new Set<string>();
  for (const spec of sorted) {
    for (const name of [spec.name, shortName(spec.name)]) {
      if (known.has(name)) throw new Error(`duplicate lens name "${name}"`);
      known.add(name);
    }
  }

  // A recursive def cannot be printed inline, so each `$defs` entry is hoisted
  // to a named interface the result types (and the def itself) refer to.
  const usedDefNames = new Set<string>();
  const defDeclarations: string[] = [];
  const scopeOf = (spec: LensSpec): DefScope => {
    const defs = isPlainObject(spec.$defs) ? spec.$defs : {};
    const names: Record<string, string> = {};
    for (const name of Object.keys(defs)) {
      const base = `${pascal(shortName(spec.name))}${pascal(name)}`;
      let typeName = base;
      let n = 2;
      while (usedDefNames.has(typeName)) typeName = `${base}${n++}`;
      usedDefNames.add(typeName);
      names[name] = typeName;
    }
    return { names, known };
  };

  const entries = sorted.map((spec) => {
    const scope = scopeOf(spec);
    for (const [name, def] of Object.entries(isPlainObject(spec.$defs) ? spec.$defs : {})) {
      const fields = isPlainObject(def) && isPlainObject(def.fields) ? def.fields : {};
      defDeclarations.push(`export interface ${scope.names[name]} ${fieldMap(fields, scope, "")}`);
    }
    const doc = spec.description ? `  /** ${spec.description.replace(/\*\//g, "*\\/")} */\n` : "";
    return (
      `${doc}  ${quoteKey(spec.name)}: {\n` +
      `    params: ${paramsType(spec)};\n` +
      `    result: ${returnsType(spec.returns, scope, "    ")};\n` +
      `  };\n` +
      `  ${quoteKey(shortName(spec.name))}: Lenses[${JSON.stringify(spec.name)}];`
    );
  });

  return `/* Generated by \`lens gen ts-sdk\` from ${sorted.length} lens document(s). Do not edit. */
import { createLensClient as createBaseClient } from "@djgrant/lenses";
export { LensOutcomeError, LensResultError } from "@djgrant/lenses";
import type {
  LensCallResult as BaseLensCallResult,
  LensClient as BaseLensClient,
  LensClientOptions,
} from "@djgrant/lenses";

/** A materialised \`{$lens, params?}\` cross-lens reference. */
export interface LensRef<Name extends string = string> {
  $lens: Name;
  params?: Record<string, unknown>;
  [key: string]: unknown;
}

${defDeclarations.length > 0 ? `${defDeclarations.join("\n\n")}\n\n` : ""}export interface Lenses {
${entries.join("\n")}
}

export type LensName = keyof Lenses;

type RequiredKeys<P> = {
  [K in keyof P]-?: [P[K]] extends [never] ? never : undefined extends P[K] ? never : K;
}[keyof P];

type ParamsArg<P> = [RequiredKeys<P>] extends [never] ? { params?: P } : { params: P };

/** A call result whose value branch is narrowed to the lens's declared shape. */
export type LensCallResult<Result> =
  | (Extract<BaseLensCallResult, { kind: "value" }> & { value: Result })
  | Exclude<BaseLensCallResult, { kind: "value" }>;

/** The client from \`@djgrant/lenses\` with \`call\` and \`value\` typed against the generated lens map. */
export interface LensClient extends Omit<BaseLensClient, "call" | "value"> {
  call<Name extends LensName>(
    input: { lens: Name; timeoutMs?: number; strict?: boolean } & ParamsArg<Lenses[Name]["params"]>
  ): Promise<LensCallResult<Lenses[Name]["result"]>>;
  /** \`call()\` unwrapped: the value, or a thrown LensOutcomeError / LensResultError. */
  value<Name extends LensName>(
    input: { lens: Name; timeoutMs?: number; strict?: boolean } & ParamsArg<Lenses[Name]["params"]>
  ): Promise<Lenses[Name]["result"]>;
}

export function createLensClient(options: LensClientOptions): LensClient {
  return createBaseClient(options) as LensClient;
}
`;
}

/** Defaulted params are optional; declared-without-default params are required. */
function paramsType(spec: LensSpec): string {
  const declarations = Object.entries(spec.params ?? {});
  if (declarations.length === 0) return "Record<string, never>";
  const fields = declarations.map(([name, declaration]) => {
    const type = typeof declaration === "string" ? declaration : declaration.type;
    const optional = typeof declaration !== "string" && declaration.default !== undefined;
    return `${quoteKey(name)}${optional ? "?" : ""}: ${paramTypes[type]}`;
  });
  return `{ ${fields.join("; ")} }`;
}

/** Lens names for LensRef targets, plus the hoisted interface name per `$defs` entry. */
interface DefScope {
  names: Record<string, string>;
  known: Set<string>;
}

/** Mirrors schema.ts's toZod: declared fields required, objects open, $lens nullable. */
function returnsType(node: unknown, scope: DefScope, indent: string): string {
  if (typeof node === "string" && node in primitiveTypes) return primitiveTypes[node];
  if (!isPlainObject(node)) return "unknown";
  if (typeof node.$lens === "string") {
    const target = scope.known.has(node.$lens) ? `<${JSON.stringify(node.$lens)}>` : "";
    return `LensRef${target} | null`;
  }
  if (typeof node.$ref === "string") return scope.names[node.$ref] ?? "unknown";
  if (node.nullable === true && typeof node.type === "string" && node.type in primitiveTypes) {
    return `${primitiveTypes[node.type]} | null`;
  }
  if (node.type === "object") {
    return isPlainObject(node.fields)
      ? fieldMap(node.fields, scope, indent)
      : "Record<string, unknown>";
  }
  if (node.type === "array") {
    const items = node.items;
    if (!isPlainObject(items)) return "unknown[]";
    if (typeof items.$ref === "string") return `Array<${scope.names[items.$ref] ?? "unknown"}>`;
    return `Array<${fieldMap(items, scope, indent)}>`;
  }
  return "unknown";
}

/** Undeclared fields pass through at runtime, hence the index signature. */
function fieldMap(fields: Record<string, unknown>, scope: DefScope, indent: string): string {
  const inner = `${indent}  `;
  const lines = Object.entries(fields).map(
    ([name, field]) => `${inner}${quoteKey(name)}: ${returnsType(field, scope, inner)};`
  );
  return `{\n${lines.join("\n")}\n${inner}[key: string]: unknown;\n${indent}}`;
}

/** "hn/item" → "HnItem". */
function pascal(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter((segment) => segment !== "")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function quoteKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function shortName(name: string): string {
  return name.slice(name.indexOf("/") + 1);
}
